MMS:
  email: 233
  password: 233
  savefolder_path: 233

RSS:
  url: 233
  key: 233333

Email:
  enable_email_notify: 1
  sender: 233
  receivers: 233
  smtp_host: 233
  smtp_port: 233
  mail_license: 114514
  send_logs: 1

onedrive:
  enable_od_upload: 0
  od_client_id: 114514
  od_client_secret: 114514
  od_redirect_uri: 114514
  od_upload_dir: abcd # relative to root， do not use '/' at the beginning
